// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OfficeCraft.Context;

#nullable disable

namespace OfficeCraft.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OfficeCraft.Models.Entities.Cliente", b =>
                {
                    b.Property<int>("PkCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PkCliente"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PkCliente");

                    b.ToTable("Clientes");

                    b.HasData(
                        new
                        {
                            PkCliente = 1,
                            Apellido = "Sosa",
                            Correo = "majo@gmail.com",
                            Nombre = "Maria"
                        },
                        new
                        {
                            PkCliente = 2,
                            Apellido = "Madrazo",
                            Correo = "gino@gmail.com",
                            Nombre = "Gino"
                        });
                });

            modelBuilder.Entity("OfficeCraft.Models.Entities.Pedido", b =>
                {
                    b.Property<int>("PkPedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PkPedido"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaPedido")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FkCliente")
                        .HasColumnType("int");

                    b.Property<int?>("FkProducto")
                        .HasColumnType("int");

                    b.HasKey("PkPedido");

                    b.HasIndex("FkCliente");

                    b.HasIndex("FkProducto");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("OfficeCraft.Models.Entities.Producto", b =>
                {
                    b.Property<int>("PkProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PkProducto"));

                    b.Property<int>("Existencia")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Precio")
                        .HasColumnType("int");

                    b.Property<string>("UrlImagenPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PkProducto");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            PkProducto = 1,
                            Existencia = 100,
                            Nombre = "Calculadora Casio Azul",
                            Precio = 1150,
                            UrlImagenPath = ""
                        },
                        new
                        {
                            PkProducto = 2,
                            Existencia = 100,
                            Nombre = "Calculadora Casio Rosa",
                            Precio = 1150,
                            UrlImagenPath = ""
                        },
                        new
                        {
                            PkProducto = 3,
                            Existencia = 100,
                            Nombre = "Mochila Chenson Negra",
                            Precio = 250,
                            UrlImagenPath = "img/productos/3"
                        },
                        new
                        {
                            PkProducto = 4,
                            Existencia = 100,
                            Nombre = "Mochila Chenson Pastel",
                            Precio = 250,
                            UrlImagenPath = "img/productos/4"
                        },
                        new
                        {
                            PkProducto = 5,
                            Existencia = 100,
                            Nombre = "Colores Norma 50pz",
                            Precio = 450,
                            UrlImagenPath = "img/productos/5"
                        },
                        new
                        {
                            PkProducto = 6,
                            Existencia = 100,
                            Nombre = "Colores Norma 36pz",
                            Precio = 250,
                            UrlImagenPath = "img/productos/6"
                        },
                        new
                        {
                            PkProducto = 7,
                            Existencia = 100,
                            Nombre = "Libreta Norma Cuadros Grandes Ferrari",
                            Precio = 90,
                            UrlImagenPath = "img/productos/7"
                        },
                        new
                        {
                            PkProducto = 8,
                            Existencia = 100,
                            Nombre = "Libreta Kiut Cuadros Grandes Pink",
                            Precio = 90,
                            UrlImagenPath = "img/productos/8"
                        },
                        new
                        {
                            PkProducto = 9,
                            Existencia = 100,
                            Nombre = "Kit de Geometria Color Morado",
                            Precio = 50,
                            UrlImagenPath = "img/productos/9"
                        },
                        new
                        {
                            PkProducto = 10,
                            Existencia = 100,
                            Nombre = "Kit de Geometria Color Azul",
                            Precio = 50,
                            UrlImagenPath = "img/productos/10"
                        });
                });

            modelBuilder.Entity("OfficeCraft.Models.Entities.Rol", b =>
                {
                    b.Property<int>("PkRoles")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PkRoles"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PkRoles");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            PkRoles = 1,
                            Nombre = "admin"
                        },
                        new
                        {
                            PkRoles = 2,
                            Nombre = "empleado"
                        });
                });

            modelBuilder.Entity("OfficeCraft.Models.Entities.Usuario", b =>
                {
                    b.Property<int>("PKUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PKUsuario"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contraseña")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FkRol")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PKUsuario");

                    b.HasIndex("FkRol");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            PKUsuario = 1,
                            Apellido = "Santos",
                            Contraseña = "1234",
                            FkRol = 1,
                            Nombre = "Jorge",
                            NombreUsuario = "joge"
                        },
                        new
                        {
                            PKUsuario = 2,
                            Apellido = "Peña",
                            Contraseña = "1234",
                            FkRol = 2,
                            Nombre = "David",
                            NombreUsuario = "davi"
                        });
                });

            modelBuilder.Entity("OfficeCraft.Models.Entities.Pedido", b =>
                {
                    b.HasOne("OfficeCraft.Models.Entities.Cliente", "Clientes")
                        .WithMany()
                        .HasForeignKey("FkCliente");

                    b.HasOne("OfficeCraft.Models.Entities.Producto", "Productos")
                        .WithMany()
                        .HasForeignKey("FkProducto");

                    b.Navigation("Clientes");

                    b.Navigation("Productos");
                });

            modelBuilder.Entity("OfficeCraft.Models.Entities.Usuario", b =>
                {
                    b.HasOne("OfficeCraft.Models.Entities.Rol", "Roles")
                        .WithMany()
                        .HasForeignKey("FkRol");

                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
